#DESCARGANDO LA IMAGEN DE NODE
FROM  node:22
#CREANDO CARPETA DE TRABAJO
WORKDIR /app
#SE VA COPIAR EL ARCHIVO DE DEPENDENCIAS
COPY package.json ./
#EJECUTAMOS EL COMANDO PARA INSTALAR LAS DEPENDENCIAS
RUN npm install
#COPIAMOS EL RESTO DE LOS ARCHIVOS
COPY . .
#EXPOSE EL PUERTO 3000
EXPOSE 3000
CMD [ "node", "src/index.js" ]
#CMD [ "turro", "npm run turro" ]
